# Copyright 2020 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.20.6-bullseye AS build

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG GOPROXY

COPY . /go/src/velero-plugin-for-microsoft-azure
WORKDIR /go/src/velero-plugin-for-microsoft-azure
RUN export GOARM=$( echo "${GOARM}" | cut -c2-) && \
    CGO_ENABLED=0 go build -v -o /go/bin/velero-plugin-for-microsoft-azure ./velero-plugin-for-microsoft-azure && \
    CGO_ENABLED=0 go build -v -o /go/bin/cp-plugin ./hack/cp-plugin


FROM registry.access.redhat.com/ubi8/ubi:8.8-854
RUN mkdir /plugins
COPY --from=build /go/bin/velero-plugin-for-microsoft-azure /plugins/
COPY --from=build /go/bin/cp-plugin /bin/cp-plugin

USER nobody:nogroup
ENTRYPOINT ["cp-plugin", "/plugins/velero-plugin-for-microsoft-azure", "/target/velero-plugin-for-microsoft-azure"]
